### ISSUE TITLE
Send Message

### ISSUE THREAD

**Issue by odenisnobre** [scraton/node-red-contrib-telegrambot-home#13]
Hi,

I am using the telegram for send message type Notification for some users.

But, so I noticed the message only sent when the user has already started a conversation with the bot.

Is there any way to send the message indepente if the user started or not the conversation with the bot through the option to start

**Comment by scraton** [comment]
Hi there!

Unfortunately this is a limitation of the Telegram API. A user must initiate a chat with the bot first. The bot can't initiate a chat with a user. Which somewhat makes sense, otherwise who knows what kind of spam we might be getting. :) Damn spammers gotta be ruining it for the rest of us.

**Comment by odenisnobre** [comment]
Ah, OK!
It makes everything feel.

Thank you very much.
