### ISSUE TITLE
sendMethod is no a valid method

### ISSUE THREAD

**Issue by oskretc** [scraton/node-red-contrib-telegrambot-home#8]
First thanks for such great nodes.  Very useful

I'm using it to create some sort of menu for my hassio.  One thing I want to do is to once the house goes "quiet" I want to ask the user if lights should go off and alarm armed. if after a certain time, there is no answer, turn of lights and arm the alarm. everything works fine until I'm trying to remove the keyboard using telegram method: ReplyKeyboardRemove. It actually works but I receive an error : "sendMethod is no a valid method"

![capture1](https://user-images.githubusercontent.com/4963991/42776916-c9b94b4e-8938-11e8-8fc5-9b73342f1fc6.PNG)

![capture2](https://user-images.githubusercontent.com/4963991/42776917-c9d74248-8938-11e8-9556-d50241a57c13.PNG)

![capture3](https://user-images.githubusercontent.com/4963991/42776918-c9f45dd8-8938-11e8-830c-f5024a1d34d7.PNG)

Am I doing something wrong?

**Comment by scraton** [comment]
That's a really cool automation idea! I'm happy to see these nodes being used in such creative ways. :)

That error message is basically saying the method you are trying to use (ReplyKeyboardRemove) isn't appropriate. The [Telegram API](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md) doesn't implement that method. The [official docs](https://core.telegram.org/bots/api#replykeyboardmarkup) show that as being a type, not a method.

What you'd want to use here is [`editMessageReplyMarkup`](https://github.com/yagop/node-telegram-bot-api/blob/release/doc/api.md#TelegramBot+editMessageReplyMarkup) (or see the [official docs](https://core.telegram.org/bots/api#editmessagereplymarkup)).

For this to work, however, you'd need the message ID that was initially sent. Since the switch node doesn't provide any feedback on the message it sends, this was seemingly impossible.

However, I've been noticing the usefulness of a timeout mechanism myself for some of my home automations. So I've implemented a native timeout feature for the switch node. If you upgrade to 0.3.0 you should see the option available in the edit node pane.

Enable the timeout, wire whatever you need up to the new "timeout" output, and you should be good to go. Let me know if that works for you, and if not, we can reopen this issue. :)

**Comment by oskretc** [comment]
Thanks for the clarification, and the update works fantastic !!! 

You can see the code simplification. very elegant solution must say.

Thanks for the great support. I'll continue developing with it and report back any issues. I might write back with some ideas I've been contemplating. 

![before](https://user-images.githubusercontent.com/4963991/42805084-25bf0f6a-89ab-11e8-820f-796416d710b6.PNG)

![after](https://user-images.githubusercontent.com/4963991/42805086-25db05ee-89ab-11e8-96d0-cdc4fe34a42b.PNG)

**Comment by scraton** [comment]
Great! Glad to hear it worked out and solved the problem.

I'd love to hear more ideas, too. So if you've got 'em, I'll see what we can get these nodes to do. :)
