### ISSUE TITLE
not able to use msg. object in telegram-payload node

### ISSUE THREAD

**Issue by SpeedyRS2** [scraton/node-red-contrib-telegrambot-home#9]
Hi, 

I'm not able to use the msg (or any other) object in the telegram-payload node.
The editor is giving a failure when I try to use this object.

![image](https://user-images.githubusercontent.com/4572175/44716939-f6249900-aabb-11e8-85a0-2fe8d1f4e5ba.png)
![image](https://user-images.githubusercontent.com/4572175/44717149-8ebb1900-aabc-11e8-89c3-a793bb5d058e.png)

Do you have an idea, what I'm doing wrong?

Thank you,
Andreas

**Comment by scraton** [comment]
Hi there!

It seems the issue is because you’re attemtping to mix some JavaScript into the JSON payload. The payload you define in the node must be plain JSON. If you want to make it dynamic, you’ll first need a function or template node to generate the payload which you can then pass to the Telegram node.

Your function node could just look like this:

```
msg.payload = { text: `Hello, *world*! ${msg.payload}`, parse_mode: "Markdown" };
return msg;
```

Be sure to remove the static payload defined in the Telegram node so it can be passed in dynamically. You can just leave it blank.

Let me know if that helps! :)

**Comment by SpeedyRS2** [comment]
thanks for the quick reply. Sometimes it could be so easy. :-)  Your suggested solution works great.
Thank you very much.

Because of the readme description I thought I could use Java Script in the node.
